channels:
  - pytorch
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.6.9
  - numba=0.45.1
  - scikit-image=0.15.0
  - scipy=1.3.1
  - tqdm=4.32.1
  - opencv=3.4.2
  - pytorch
  - torchvision
  - pytest
  - pytorch=1.2.0=py3.6_cpu_0
  - torchvision=0.4.0=py36_cpu

